### ISSUE TITLE
Missing documentation on connection timeout for redis

### ISSUE THREAD

**Issue by erikttv** [integreat-io/integreat-transporter-redis#40]
It would be helpful to have documentation on how to use connection timeout for redis.

**Comment by kjellmorten** [comment]
Hi, @erikttv.

Is it the `expire` option you're thinking of here or something else?

**Comment by erikttv** [comment]
I am talking about the `connectionTimeout` that can be included in the transporter.

**Comment by kjellmorten** [comment]
Ah, of course. Thanks for the clarification, @erikttv!

I'll document this as soon as I get the chance, but a quick explanation in case you need it: When `connectionTimeout` is set, as a number of milliseconds, the Redis connection will be renewed after this timeout regardless of the state of the connection.

(Anecdote: This was added because of a setup behind a customer's firewall, where the Redis connection would just stop working after a time, and the administrators of the firewall couldn't figure out why. So we set this option to a timeout that was shorter than the timeout of the firewall, and things worked like a charm again.)

**Comment by kjellmorten** [comment]
Updated the README now, @erikttv. Thanks for bringing it to my attention!
